# Generated by Django 2.2.6 on 2019-11-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pomodoro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('length', models.IntegerField(help_text='time in minutes')),
                ('descript', models.TextField()),
            ],
            options={
                'verbose_name': 'pomodoro',
                'verbose_name_plural': 'pomodoros',
            },
        ),
    ]
