# Generated by Django 2.2.6 on 2019-11-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pomodoro',
            old_name='descript',
            new_name='description',
        ),
    ]
