# Generated by Django 2.2.6 on 2019-11-03 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('priority', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('backgroud_image', models.ImageField(upload_to='')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('expected_end_time', models.DateTimeField(blank=True, null=True)),
                ('real_end_time', models.DateTimeField(blank=True, null=True)),
                ('expected_total_time', models.IntegerField()),
                ('real_total_time', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'WORKBOARD',
                'verbose_name_plural': 'WORKBOARD',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('priority', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('expected_end_time', models.DateTimeField(blank=True, null=True)),
                ('real_end_time', models.DateTimeField(blank=True, null=True)),
                ('expected_total_time', models.IntegerField()),
                ('real_total_time', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('UN', 'Unplanned'), ('SC', 'Scheduled'), ('CM', 'Completed'), ('CN', 'Cancelled')], default='UN', max_length=2)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dork.Project')),
            ],
            options={
                'verbose_name': 'TASK',
                'verbose_name_plural': 'TASK',
            },
        ),
    ]
