# Generated by Django 2.2.6 on 2019-12-05 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dork.Project')),
            ],
            options={
                'verbose_name': 'SUBTASK',
                'verbose_name_plural': 'SUBTASKS',
            },
        ),
    ]
