# Generated by Django 2.2.6 on 2020-02-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dork', '0007_workboard_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workboard',
            old_name='user',
            new_name='owner',
        ),
    ]
